# Welcome to My website!
# Template credit to: Sarah Pratt; https://github.com/sarahpratt

title: Olatunji Damilare Emmanuel 
email: olatunjidamilare.e@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Olatunji Damilare Emmanuel's website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Damilare1012

# Build settings
markdown: kramdown
# theme: minima
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
sass:
  style: compressed

google_analytics: UA-119603762-1

include:
  - static

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

